### ISSUE TITLE
On Windows have install specify current directory for download

### ISSUE THREAD

**Issue by dmcglinn** [ropensci/ecoretriever#44]
The `retriever` by default downloads datasets to the desktop on a Windows OS (see #43). Therefore, the default behavior of the function `install()` needs to updated so that the current working directory is used unless another directory is specified.

**Comment by ethanwhite** [comment]
Fixed in https://github.com/weecology/retriever/commit/5267d2651e3ef290cc33e3d51c10d683ae2c70eb
