### ISSUE TITLE
Support new subdirectory functionality from retriever

### ISSUE THREAD

**Issue by ethanwhite** [ropensci/ecoretriever#55]
As of https://github.com/weecology/retriever/commit/61929bd1ff0691d6789c75d44d8f749cc80bda95 it is possible for the `download` engine of the `retriever` to keep downloaded files in the archive file subdirectory structure. This is useful for downloading GIS data and keeping it in the standard structure and should be a supported option in the R-wrapper.

**Comment by dmcglinn** [comment]
What is the `archive file subdirectory`? Sorry I'm confused what the new feature is here.

**Comment by ethanwhite** [comment]
Basically `subdir` should be an optional argument that is set to `FALSE` by default. If it is set to `TRUE` then the command should be run as `retriever download DATASET --subdir`. I'm busy the rest of today, but if you would prefer a PR let me know and I should be able to put one in this evening. Thanks.

**Comment by dmcglinn** [comment]
solved in #56
