### ISSUE TITLE
conn_file instructions

### ISSUE THREAD

**Issue by davharris** [ropensci/ecoretriever#63]
I think I found two problems with the instructions this package provides for users in terms of their conn_file.

1) The man page recommends comma-separated values, but [an error message about the same thing](https://github.com/ropensci/ecoretriever/blob/4efb4812a8cac18ce86f381d498627b59434ed10/R/ecoretriever.R#L34-L37) recommends space-delimited.

2) Users might take `port 1111` literally. A more obvious placeholder such as `portnumber` might be better.

**Comment by dmcglinn** [comment]
Thanks for these Dave! These both sound like reasonable suggestions. I've just submitted the PR

**Comment by ethanwhite** [comment]
Fixed by 858c3e0657f7502bd451d5d738bdf87d10399389.
