### ISSUE TITLE
won't work with RStudio + anaconda python

### ISSUE THREAD

**Issue by sdtaylor** [ropensci/ecoretriever#70]
I'm running into the same issue as #10 and #53  

I'm running Rstudio and miniconda on Ubuntu 15.10. I've traced it back to the `Sys.which('retriever')` call in `ecoretriever.R`. 

When I run it in Rstudio it fails because it can't find retriever in my local `~/miniconda3/bin` path

```
> Sys.which('retriever')
retriever 
       "" 
> system('echo $PATH')
/home/shawn/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/home/shawn/bin//bin
> 
```

Even though it works with R from the command line

```
> Sys.which('retriever')
                             retriever 
"/home/shawn/miniconda3/bin/retriever" 
> system('echo $PATH')
/home/shawn/miniconda3/bin:/home/shawn/anaconda3/bin:/home/shawn/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/home/shawn/bin//bin
> 
```

Looks like RStudio does not get access to user configured paths. So it can't find `retriever` installed in my `~/miniconda` directory (same would be true for anaconda). This is an issue with [other](https://support.rstudio.com/hc/en-us/community/posts/203561546-RStudio-can-t-detect-pdflatex-No-Tex-installation-detected-) software too. I'll look into this more when I have time.

**Comment by dmcglinn** [comment]
Thanks for reporting @sdtaylor! Please let us know if you find a solution.

**Comment by beecycles** [comment]
I'm seeing the same problem.  Using OSX 10.12.2, Python 3.5.  In RStudio: "retriever is not on your path." Works fine from Terminal.

**Comment by bleds22e** [comment]
I'm experiencing the same issue on Windows 7, R 3.2.3, RStudio 1.0.44

**Comment by KristinaRiemer** [comment]
Also the same problem, OSX 10.11.1, R 3.3.1, RStudio 0.99.903

**Comment by emchristensen** [comment]
same, Windows 10

**Comment by ethanwhite** [comment]
Just to summarize: our broad test of the `ecoretriever` this morning revealed that this is now a universal issue across all operating systems.

**Comment by sdtaylor** [comment]
A straightforward workaround for this would be, if `retriever` isn't found in the default python path, to search for it in the default anaconda/miniconda paths. In linux (and I assume mac) it would be one of `~/anaconda2/, ~/anaconda2, ~/miniconda2, ~/miniconda3`. In windows it's another location that would need some detective work to make sure it stable.

**Comment by ethanwhite** [comment]
heh! I was literally just exploring this possibility :)

**Comment by ethanwhite** [comment]
Can everyone on this issue edit their reports to include the output of `which retriever` from the command line? That will help us map a plan for looking for these paths. Thanks.

**Comment by sdtaylor** [comment]
Here is some logic that should work. Hopefully not too hacky.  
https://github.com/sdtaylor/ecoretriever/commit/fe70e2edd8d2ce0bbde7fb7a5620af7fb8a0e492

**Comment by ethanwhite** [comment]
Looks great. Thanks @sdtaylor!

I just did a fresh install of Anaconda 3 on windows and got `C:\Users\USERNAME\Anaconda3\Scripts\retriever`.

`Sys.getenv('HOME')` returns `C:\\Users\\USERNAME\\Documents` on this machine, which is the same as one of the desktop's at work, but my Windows machine at work returned `C:\\Users\\USERNAME` so we should probably check both just to be sure.

**Comment by sdtaylor** [comment]
For windows it might  be better to use the username then.  

```
username = Sys.getenv('USER')
for (possible_path in c('/Anaconda3/Scripts','/Anaconda2/Scripts','/Miniconda3/Scripts','/Miniconda2/Scripts')) {
          Sys.setenv(PATH = paste0(Sys.getenv('PATH'),':','C:\Users\',username,possible_path))
    }
```

**Comment by ethanwhite** [comment]
` Sys.getenv('USER')` returns an empty string on my office Windows machine.

**Comment by ethanwhite** [comment]
Actually, looks like I was wrong. My work machine is also returning `C:\\Users\\USERNAME\\Documents` for `HOME`, so we should be able to just use it and chop off the `Documents`.

**Comment by sdtaylor** [comment]
Can you test if this works? Should return just `C:\\Users\\USERNAME`

`basepath = dirname(Sys.getenv('HOME'))`

**Comment by ethanwhite** [comment]
Yep, it works!

**Comment by ethanwhite** [comment]
Reopening until we get a few more successful tests in.

**Comment by ethanwhite** [comment]
@beecycles @bleds22e @KristinaRiemer @emchristensen - can you run:

```
devtools::install_github("ropensci/ecoretriever")
```

And then

```
ecoretriever::datasets()
```

and let us know if you get something different than the

```
The retriever is not on your path and may not be installed...
```

error.

**Comment by ethanwhite** [comment]
Based on reported tests in #73 this looks to be working properly now. 🎉
