### ISSUE TITLE
`fetch` returns empty named list

### ISSUE THREAD

**Issue by ethanwhite** [ropensci/ecoretriever#75]
On multiple operating systems we are seeing the `fetch` command returning an empty named list instead of a named list holding data frames with the appropriate data. Ubuntu 16.04 and OS X.

**Comment by henrykironde** [comment]
Fetch fails on several scripts

Fetch works on a few of the data retriever scripts like `Portal`, `iris `
and fails on several like poker-hands, `gentry-forest-transects`, `car-eval`

Gentry = ecoretriever::fetch('poker-hands')
Gentry = ecoretriever::fetch('gentry-forest-transects')
Gentry = ecoretriever::fetch('car-eval')

**Comment by ethanwhite** [comment]
@henrykironde are you sure that's tested on the most recent version. That was the old behavior for me but master now works fine (just tested on `car-eval`). If you already had the library loaded you need to restart R after the github based install. If that doesn't work can report the OS and R details so we can start to untangle where the issue is?

**Comment by henrykironde** [comment]
Test on all machines work fine, I guess after restarting

**Comment by sdtaylor** [comment]
This works for me on Ubuntu 16.04 and with the current version. 

`ecoretriever::fetch('gentry-forest-transects')`

**Comment by ethanwhite** [comment]
Awesome. Thanks both.
