### ISSUE TITLE
`.retriever` directory created in different location in RStudio on Windows

### ISSUE THREAD

**Issue by ethanwhite** [ropensci/ecoretriever#81]
For reasons that I cannot currently fathom, running `ecoretriever::datasets()` in RStudio on Windows (10) creates the `.retriever` directory in `C:\Users\username\Documents` instead of `C:\Users\username` where it should be. The good news is it just operates as it's own separate installation, so if your only using either RStudio or the CLI there won't be any confusion, but it just cost me 30 pretty confused minutes.

**Comment by ethanwhite** [comment]
This looks like it is happening because `Sys.getenv('HOME')` in RStudio on Windows returns `"C:/Users/username/Documents"` instead of `"C:/Users/username/"`. We should be able to check for the extra `Documents` and strip it off it it occurs.

**Comment by ethanwhite** [comment]
Actually, my solution won't work because the core retriever code is handling things. It's really weird that somehow RStudio is changing how the core retriever thinks about the home directory.

**Comment by ethanwhite** [comment]
Current guess is that `HOME_DIR = os.path.expanduser('~/.retriever/')` from the core retriever is run from inside RStudio (via Python) it ends up behaving like `Sys.getenv('HOME')`. Haven't figure out how to prove this just yet, but I'm experimenting with running something like:

```
system("python -c 'print(os.path.expanduser('~/.retriever/'))'")
```

from inside RStudio, but I haven't gotten it working yet.

**Comment by henrykironde** [comment]
This is the same as explained in the PR 
```
I have tried to find the problem but it seems this is a windows + Rstudio + environmental path variables problem.
Run Sys.getenv() in Rstudio, notice that the home path is different from your expected path.
Try setting the HOME path in the Environmental variables
```
This happens because the  path variable is not set well.  #90

**Comment by henrykironde** [comment]
I think we should close this and instead let users know that when using `Rstudio`, make sure the path to the `HOME` Environmental variables is set to your actual home not the home of `RStudio` which I think will default to the Document folder `'C:/Users/username/Documents'`

**Comment by ethanwhite** [comment]
Ah yes, sorry for missing that. I feel like we should be able to solve this, so my vote would be to leave it open, but I also don't think we should put off releasing for this since it's a fairly minor issue with a new feature on a single system configuration.
